-- 코드를 입력하세요
SELECT A.ANIMAL_ID
    ,A.NAME 
FROM ANIMAL_INS AS A
INNER JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE DATEDIFF(B.DATETIME ,A.DATETIME) 
ORDER BY DATEDIFF(B.DATETIME ,A.DATETIME) DESC 
LIMIT 2