-- 코드를 입력하세요
SELECT A.FOOD_TYPE AS FOOD_TYPE
    ,A.REST_ID AS REST_ID
    ,A.REST_NAME AS REST_NAME
    ,A.FAVORITES AS FAVORITES
FROM REST_INFO AS A
WHERE (A.FAVORITES , A.FOOD_TYPE) IN 
(SELECT MAX(FAVORITES) , FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE)
ORDER BY A.FOOD_TYPE DESC
