-- 코드를 입력하세요
SELECT A.ANIMAL_TYPE AS ANIMAL_TYPE
        , (CASE  WHEN A.NAME IS NULL THEN 'No name'
        ELSE A.NAME END) AS NAME
        , A.SEX_UPON_INTAKE AS SEX_UPON_INTAKE
        
FROM ANIMAL_INS AS A