-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR
    ,MONTH(B.SALES_DATE) AS MONTH
    ,A.GENDER
    ,COUNT(DISTINCT((B.USER_ID))) AS USERS
FROM USER_INFO AS A
INNER JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR(B.SALES_DATE) ,MONTH(B.SALES_DATE) , A.GENDER
HAVING A.GENDER IS NOT NULL
ORDER BY YEAR(B.SALES_DATE) , MONTH(B.SALES_DATE) , A.GENDER