SELECT A.ROUTE
    ,CONCAT(ROUND(SUM(A.D_BETWEEN_DIST) ,1) , 'km' )AS TOTAL_DISTANCE
    ,CONCAT(ROUND(AVG(A.D_BETWEEN_DIST) ,2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE AS A
GROUP BY A.ROUTE 
ORDER BY ROUND(SUM(A.D_BETWEEN_DIST) ,1) DESC