SELECT A.FLAVOR
FROM FIRST_HALF AS A
INNER
JOIN (SELECT FLAVOR , SUM(TOTAL_ORDER) AS TOTAL_ORDER  FROM JULY GROUP BY FLAVOR) AS B
ON A.FLAVOR = B.FLAVOR
GROUP 
    BY B.FLAVOR
ORDER
    BY B.TOTAL_ORDER + A.TOTAL_ORDER DESC
LIMIT 3