-- 코드를 입력하세요
WITH CAR AS(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' and '2022-10-31'
    group by CAR_ID
    having count(*) >= 5
)
SELECT MONTH(START_DATE) AS MONTH
       ,CAR_ID
       ,COUNT(CAR_ID) AS RECORDS
FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN(SELECT CAR_ID FROM CAR ) AND MONTH(START_DATE) BETWEEN 8 AND 10 
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC ,CAR_ID DESC



