-- 코드를 입력하세요
SELECT SUBSTR(A.PRODUCT_CODE ,1,2) AS 'CATEGORY'
    ,COUNT(SUBSTR(A.PRODUCT_CODE ,1,2)) AS PRODUCTS
FROM PRODUCT AS A
GROUP
    BY SUBSTR(A.PRODUCT_CODE ,1,2)
ORDER
    BY SUBSTR(A.PRODUCT_CODE ,1,2)  ASC