SELECT B.SCORE AS SCORE
    ,A.EMP_NO AS EMP_NO
    ,A.EMP_NAME AS EMP_NAME
    ,A.POSITION AS POSITION
    ,A.EMAIL AS EMAIL
FROM HR_EMPLOYEES AS A
JOIN (SELECT EMP_NO , SUM(SCORE) AS SCORE
FROM HR_GRADE
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1) AS B
ON A.EMP_NO = B.EMP_NO

