SELECT A.DEPT_ID AS DEPT_ID
      ,A.DEPT_NAME_EN AS DEPT_NAME_EN
      ,B.SAL AS AVG_SAL
FROM HR_DEPARTMENT AS A
INNER JOIN (SELECT ROUND(AVG(SAL),0) AS SAL , DEPT_ID FROM HR_EMPLOYEES GROUP BY DEPT_ID) AS B
ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID
ORDER BY B.SAL DESC
