SELECT COUNT(FISH_TYPE) AS FISH_COUNT
       ,MAX(A.LENGTH) AS MAX_LENGTH
       ,A.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO AS A  
GROUP BY  A.FISH_TYPE
HAVING AVG(CASE 
            WHEN A.LENGTH IS NULL THEN 10
            ELSE A.LENGTH END )  >= 33
ORDER BY A.FISH_TYPE ASC